# -*- coding: utf-8 -*-
"""Restaurant_sales_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGkQtN8rDhGxE-hFxiL9Po77IKQGnc9v
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/archive (3).zip")
df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')
df['Total_Sale'] = df['Price'] * df['Quantity']
df['Month'] = df['Date'].dt.month_name()
df['Weekday'] = df['Date'].dt.day_name()

top_cities = df.groupby('City')['Total_Sale'].sum().sort_values(ascending=False).head(5)

sns.set(style="whitegrid")
plt.figure(figsize=(10,6))
sns.barplot(x=top_cities.values, y=top_cities.index)
plt.title("Top 5 Cities by Revenue")
plt.xlabel("Revenue")
plt.ylabel("City")
plt.show()

top_products = df.groupby('Product')['Quantity'].sum().sort_values(ascending=False).head(5)

plt.figure(figsize=(10,6))
sns.barplot(x=top_products.values, y=top_products.index, palette="viridis")
plt.title("Top 5 Products by Quantity Sold")
plt.xlabel("Quantity")
plt.ylabel("Product")
plt.show()

purchase_type = df.groupby('Purchase Type')['Total_Sale'].sum()

plt.figure(figsize=(6,6))
purchase_type.plot(kind='pie', autopct='%1.1f%%', startangle=90)
plt.title("Revenue by Purchase Type")
plt.ylabel("")
plt.show()

monthly_revenue = df.groupby('Month')['Total_Sale'].sum().reindex([
    'January','February','March','April','May','June',
    'July','August','September','October','November','December'
]).dropna()

plt.figure(figsize=(12,6))
sns.lineplot(x=monthly_revenue.index, y=monthly_revenue.values, marker='o', color='teal')
plt.title("Monthly Revenue Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

weekday_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
weekday_revenue = df.groupby('Weekday')['Total_Sale'].sum().reindex(weekday_order)

plt.figure(figsize=(10,6))
sns.barplot(x=weekday_revenue.index, y=weekday_revenue.values, palette='coolwarm')
plt.title("Revenue by Weekday")
plt.xlabel("Day of Week")
plt.ylabel("Revenue")
plt.show()

payment_counts = df['Payment Method'].value_counts()

plt.figure(figsize=(8,6))
sns.barplot(x=payment_counts.index, y=payment_counts.values)
plt.title("Payment Method Distribution")
plt.xlabel("Payment Method")
plt.ylabel("Number of Transactions")
plt.xticks(rotation=45)
plt.show()

product_perf = df.groupby('Product').agg({
    'Total_Sale': 'sum',
    'Quantity': 'sum'
}).sort_values(by='Total_Sale', ascending=False)

product_perf.plot(kind='bar', figsize=(12,6))
plt.title("Product Performance: Revenue vs Quantity")
plt.xlabel("Product")
plt.ylabel("Total")
plt.xticks(rotation=45)
plt.legend(["Revenue", "Quantity"])
plt.tight_layout()
plt.show()

daily_sales = df.groupby('Date')['Total_Sale'].sum()

plt.figure(figsize=(14,6))
daily_sales.plot(kind='line', color='green')
plt.title("Daily Sales Trend")
plt.xlabel("Date")
plt.ylabel("Total Revenue")
plt.grid(True)
plt.tight_layout()
plt.show()